development: &defaults
  adapter: postgresql
  database: crypto_group_buy_development
  username: alex
  password: password
  host: localhost
  min_messages: warning

test:
  <<:       *defaults
  database: crypto_group_buy_test
  min_messages: error

production:
  <<:       *defaults
  database: crypto_group_buy_production

rake:
  <<:       *defaults

